server:
  port: 11000
  servlet:
    session:
      timeout: 30

spring:
  datasource:
    password: ToKreDi*nJ
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.192.19.163:1521/orcl
    username: ZHFTYJJCPT

security:
  basic:
    enabled: true
#  oauth2:
#    client:
#      client-id: admin-oauth
#      client-secret: 123-oauth

logging:
  level:
    root: INFO